@php $c = $candidate ?? null; @endphp
<div class="row">
    <div class="col-md-6 mb-3"><label class="form-label">First Name <span class="text-danger">*</span></label><input name="first_name" value="{{ old('first_name', $c->first_name ?? '') }}" class="form-control @error('first_name') is-invalid @enderror" required>@error('first_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6 mb-3"><label class="form-label">Last Name <span class="text-danger">*</span></label><input name="last_name" value="{{ old('last_name', $c->last_name ?? '') }}" class="form-control @error('last_name') is-invalid @enderror" required>@error('last_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6 mb-3"><label class="form-label">Email <span class="text-danger">*</span></label><input type="email" name="email" value="{{ old('email', $c->email ?? '') }}" class="form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6 mb-3"><label class="form-label">Phone <span class="text-danger">*</span></label><input name="phone" value="{{ old('phone', $c->phone ?? '') }}" class="form-control @error('phone') is-invalid @enderror" required>@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4 mb-3"><label class="form-label">Date of Birth</label><input type="date" name="dob" value="{{ old('dob', isset($c->dob) ? \Carbon\Carbon::parse($c->dob)->format('Y-m-d') : '') }}" class="form-control @error('dob') is-invalid @enderror">@error('dob')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4 mb-3"><label class="form-label">Gender</label><select name="gender" class="form-select"><option value="">—</option>@foreach(['Male','Female','Other'] as $g)<option @selected(old('gender',$c->gender ?? '')==$g)>{{ $g }}</option>@endforeach</select></div>
    <div class="col-md-4 mb-3"><label class="form-label">Nationality</label><input name="nationality" value="{{ old('nationality', $c->nationality ?? '') }}" class="form-control"></div>
    <div class="col-md-6 mb-3"><label class="form-label">Passport No</label><input name="passport_number" value="{{ old('passport_number', $c->passport_number ?? '') }}" class="form-control"></div>
    <div class="col-md-6 mb-3"><label class="form-label">Address</label><input name="address" value="{{ old('address', $c->address ?? '') }}" class="form-control"></div>
    <div class="col-md-4 mb-3"><label class="form-label">Destination</label><select name="destination" class="form-select">@foreach(['UK','Canada','Australia','USA','New Zealand','Ireland'] as $d)<option @selected(old('destination',$c->destination ?? 'UK')==$d)>{{ $d }}</option>@endforeach</select></div>
    <div class="col-md-4 mb-3"><label class="form-label">Study Level</label><select name="study_level" class="form-select">@foreach(['Foundation','Undergraduate','Postgraduate','Diploma','PhD','English'] as $l)<option @selected(old('study_level',$c->study_level ?? '')==$l)>{{ $l }}</option>@endforeach</select></div>
    <div class="col-md-4 mb-3"><label class="form-label">Subject Interest</label><input name="subject" value="{{ old('subject', $c->subject ?? '') }}" class="form-control"></div>
    <div class="col-md-4 mb-3"><label class="form-label">Source</label><select name="source" class="form-select">@foreach(['Walk-in','Referral','Website','Social Media','Agent','Event'] as $s)<option @selected(old('source',$c->source ?? '')==$s)>{{ $s }}</option>@endforeach</select></div>
    <div class="col-md-4 mb-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['new','contacted','counselling','applied','offered','visa','enrolled','rejected'] as $s)<option @selected(old('status',$c->status ?? 'new')==$s)>{{ $s }}</option>@endforeach</select></div>
    <div class="col-md-4 mb-3"><label class="form-label">Assign Staff</label><select name="assigned_to" class="form-select"><option value="">Unassigned</option>@foreach(($staff ?? []) as $u)<option value="{{ $u->id }}" @selected(old('assigned_to',$c->assigned_to ?? '')==$u->id)>{{ $u->name }}</option>@endforeach</select></div>
</div>
