@php $a = $application ?? null; @endphp
<div class="row">
    <div class="col-md-6 mb-3"><label class="form-label">Candidate <span class="text-danger">*</span></label><select name="candidate_id" class="form-select @error('candidate_id') is-invalid @enderror" required><option value="">Select…</option>@foreach(($candidates ?? []) as $c)<option value="{{ $c->id }}" @selected(old('candidate_id', $a->candidate_id ?? request('candidate'))==$c->id)>{{ $c->first_name }} {{ $c->last_name }} ({{ $c->email }})</option>@endforeach</select>@error('candidate_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6 mb-3"><label class="form-label">University <span class="text-danger">*</span></label><select name="university_id" class="form-select" required><option value="">Select…</option>@foreach(($universities ?? []) as $u)<option value="{{ $u->id }}" @selected(old('university_id',$a->university_id ?? request('university'))==$u->id)>{{ $u->name }}</option>@endforeach</select></div>
    <div class="col-md-6 mb-3"><label class="form-label">Course <span class="text-danger">*</span></label><select name="course_id" class="form-select" required><option value="">Select…</option>@foreach(($courses ?? []) as $c)<option value="{{ $c->id }}" @selected(old('course_id',$a->course_id ?? request('course'))==$c->id)>{{ $c->name }}</option>@endforeach</select></div>
    <div class="col-md-6 mb-3"><label class="form-label">Intake <span class="text-danger">*</span></label><select name="intake" class="form-select" required>@foreach(['Jan','May','Sep'] as $m)@foreach([date('Y'),date('Y')+1] as $y)@php $v="$m $y"; @endphp<option @selected(old('intake',$a->intake ?? '')==$v)>{{ $v }}</option>@endforeach @endforeach</select></div>
    <div class="col-md-6 mb-3"><label class="form-label">Priority</label><select name="priority" class="form-select">@foreach(['low','normal','high','urgent'] as $p)<option @selected(old('priority',$a->priority ?? 'normal')==$p)>{{ $p }}</option>@endforeach</select></div>
    <div class="col-md-6 mb-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['draft','submitted','offer_received','deposit_paid','cas_issued','visa_applied','visa_granted','visa_refused','enrolled','deferred','cancelled'] as $s)<option @selected(old('status',$a->status ?? 'draft')==$s)>{{ $s }}</option>@endforeach</select></div>
    <div class="col-12 mb-3"><label class="form-label">Notes</label><textarea name="notes" rows="3" class="form-control">{{ old('notes', $a->notes ?? '') }}</textarea></div>
</div>
